/**
 * App icon as embedded base64 PNG.
 * This avoids path resolution issues between dev and production builds.
 */

import { nativeImage, app } from 'electron';
import { join } from 'path';
import { existsSync } from 'fs';

// Base64-encoded icon.png from build/icon.png (512x512 PNG)
const ICON_BASE64 = 'iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAASQUlEQVR4nO3dP4hk2XXA4TfyJEq87OaaRFHDsImVjTAYPBtIiRJhFMig2IlCJ4qUOHSi2GAFg9nEiR1IAoHQZFZiFiZSMgPGYJCQEkViHKzK7q3uqnp/7nv3nHu+DwRiZ7rr1uuePr9361W/aQIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIDbnvRewJ7+4q++/b73GgDI7Vc//3TIWTnUkzLwAdjbKEEwxJMw+AE4WvYQSL14gx+A3rKGQMpFG/wARJMtBL7UewFLGf4ARJRtPqUKgGwHF4BaMs2pFNsVmQ4oAExT/JcEwu8AGP4AZBR9foUOgOgHDwCuiTzHQgcAALCPsAEQuZoAYK6o8yxkAEQ9WACwRsS5Fi4AIh4kANgq2nwLFwAAwP5CBUC0OgKAliLNuVABAAAcI0wARKoiANhLlHn3tPcCIvrZn/324p/99R8/bP54v/juv1/8s7/88TeaP96v//75xT/76j981vzxAIgnxO8pjlJD1wb/uRYhcG3wn2sRAtcG/zkhALCv3vcKCPMSQG9Lhv+av39uyfBf8/fPLRn+a/4+ALkIgGn9MF/7cWuH+dqPWzvMRQDAuMoHwNYz+aUfv/VMfunHbx3iIgBgTN0DoOfr/1uH/9LPs3X4L/08rYa3CABor/f1b90DAAA4XtkAaHX2P/fztTr7n/v5Wp+12wUAGEvZAACAygQAABQkAACgIAEAAAUJAAAoSAAAQEFlA6D1Xf1ufb7Wd/W79fla38zHzYEAxlI2AACgstIB0GoXYO7nabULMPfztDprd/YPMJ7SATBN2yNg6cdvjYClH791eBv+AGMqHwDTtD4C1n7c2ghY+3Frh7jhDzAuAfAnS4f51p2DpcN8687B0mFu+AOM7UnvBfS+HeJjrt3Yp/W7B6bp+o19Wr97YJqu39jH4Ac4zq9+/mm3OSwAAKCTngHgJQAAKEgAAEBBAgAAChIAAFCQAACAggQAABQkAACgIAEAAAUJAAAoSAAAQEECAAAKEgAAUJAAAICCBAAAFCQAAKAgAQAABQkAACjoae8F/M9//1fvJQBAOXYAAKAgAQAABQkAAChIAABAQQIAAAoSAABQkAAAgIIEAAAUJAAAoCABAAAFCQAAKEgAAEBBAgAAChIAAFCQAACAggQAABQkAACgIAEAAAUJAAAoSAAAQEECAAAKEgAAUJAAAICCBAAAFCQAAKAgAQAABQkAAChIAABAQQIAAAoSAABQkAAAgIIEAAAUJAAAoCABAAAFCQAAKEgAAEBBAgAAChIAAFDQ094LyOTu+ce9lzDbm8/+s/cSuvrdb37bewnhfPDRh4c9luP/0JHHH+YQADNkGvwnpzVXCwGD57LTsdlzEDn+lx1x/GEJLwEwDMNnnr2Ok+M/j+NEFALghoxn//dlX/9cfqgu0/p4Of7LOF5EIABIzw/TdVodN8d/HceN3gQAABQkAG7IfhFd9vXf4ixqm63Hz/HfxvGjJwEAAAV5G+AMp7PoTBfUjX7mD8A2AmABQxWAUXgJAAAKEgAAUJCXACjh29/93uGP+emP/+nwx4zK8Yd47AAwvB7Dp+fjRuP4Q0wCgKH1HgK9H7+33s+/9+NDZAIAAAoSAABQkABgaL0vBOv9+L31fv69Hx8iEwAMr9cQMHw+5/hDTE96L+DZ3Yv3vddAXm6mst0HH324+mMd/+22HH/ye/vmdbc5bAcAAAoSAABQkAAA4KqvfOenj/5/chMAAFx0GvjnEXD6H3m5F8ACd88/7r2E2dy6GNjiseF+67+9e/Vy1zXRlgCYIdPgPzmtWQgAS609sxcDuQgAAP5Pq219MRCfALgh49n/fXfPP7YLANy05+v5YiAmAUAZz//uP3ovYbbPfvS13kto7sk//03vJcz2/m//pfcSDjVn+N8f3FtiQQzE4TcB3pB9B2Caxr4OYO5voss0/E+OioAjfhNgpuF/clQE9PxNgHMH+bVB3WrnoGoM9PxNgAJghswRMPLwn6Z5Ayjj8D85IgL2DoCMw//kiAjoFQBLz/pbfc45KsWAXwUMO8k8/Kcp//ozD/9pyr/+S/YY/qePOf2P+FwDMMPpLDrTTsDoZ/7Aci22/Odae82AeDiOAFjAUAWy2uusf45WFxDSlgAAGFzP4X/tcc7X5ez/WAIAYFBHbvmvYWegLxcBMrTs76fPvv7s76fPvP65Z/1RzrqjrKMSAcDwsg7RrOs+l3WIZl333Lv0GbgIAErINkyzrfeWbMM023pPsp3105drAChjtKGaTdahmoWzfpYSAACJRb/Qj7gEAEBSzvrZwjUAAAkZ/mxlB4DUPvjow9l3pOOhrTeicfy3WXP8bfnTigAASMJZPy0JANJzFrpOq9vQOv7rLDn+zvrZg2sAGEKve6pn1fp49T7+92+bnOEWyq2Hv/f2s8aT3gt4dvfife81MA5norftOax7HP/7A/+zH33tYgBE+T0Qewx/8nr75nW3OewlgAXunn/cewmzVb118emHqxB46Iiz9COP/9Iz/d5hYMufaOwAzJBp8J+rGgKMbe87x/UcrM76a7EDADDTEbeNvfQYew9ew58j2QG4IfPZ/4ldAEYQ9X7xLQayLf+67AAAXLH1zHjPeNi6W+Csn14EABBWqzPjx/587x2Fxz7//XU466c3LwHMkPllANv/ZNXrzDjKSw0Gfw1eAgC4p+e2eI/dgjlrgNbsACyQaSfAmT8ZZdsW3yMMojw3jtFzB0AAACGMcjHc2ijI8Nxoz0sAQGmjDP9purzOa88xy3NjLAIA6Cbblv8Wl64tGOG5kZMAALoY6ax/rdGfH7EJAOBQlc76ITIBABzGWT/E8aXeCwBqMPwhFjsAwK5s+UNMAgDYjbN+iMtLAMAuDH+IzQ4A0JQtf8hBAADNOOuHPAQAsJmzfsjHNQBwkNOQjHK/+VbmnvUb/hCLHQDY2WMD8rH/lnFA2vKHvNwOGHbS6kw/4gC15Q9tuB0wDKblNn+03QJn/TAGAQANHfX6/qXH2XvwGv4wDgEADUS5sG+v3QJb/jAeAQAbLB38lwbkngGxdbfAWT+MyUWAsEKrwd/yMVq4v05n/bC/nhcBCgBY4IjB33oNezH4YTvvAoAEIgz/S5/36Cgw/CE/AQA3RBn8ax5zjzAw/GEMAgAuyDD4b2m5WxDx+QHrCQA4M8Lgv2bNbkG25wjcJgDgT0Yf/Ldc2i0Y7XkCnxMAlFd98F9T6blCNW4HTGmGP1CVHQBKMviB6gQApRj8AJ8TAJRg8AN8kQBgaAY/wOMEAEMy+AGu8y4AhmP4A9xmB4BhGPwA8wkA0jP4AZYTAKRl8AOsJwAYnsEP8JCLAEnr1mB/9+ql4Q9wgQBgSAY/wHUCgNTOB72zfoB5XAPAEAx9gGXsAJCe4Q+wnAAAgIIEAAAUJAAAoCABAAAFCQAAKEgAAEBBAgAAChIAAFCQAACAggQAABQkAACgIAEAAAUJAAAoSAAAQEECAAAKEgAAUJAAAICCBAAAFCQAAKAgAQAABQkAAChIAABAQQIAAAoSAABQkAAAgIIEAAAUJAAAoCABAAAFCQAAKEgAAEBBAgAAChIAAFCQAACAggQAABQkAACgIAEAAAUJAAAoSAAAQEECAAAKEgAAUJAAAICCBAAAFCQAAKAgAQAABQkAAChIAABAQQIAAAoSAABQkAAAgIIEAAAUJAAAoCABAAAFCQAAKEgAAEBBAgAAChIAAFCQAACAggQAABQkAACgIAEAAAUJAAAoSAAAQEECAAAKEgAAUJAAAICCBAAAFCQAAKAgAQAABQkAAChIAABAQQIAAAoSAABQkAAAgIIEAAAUJAAAoKCnvRcALfz+Hz/pvQQa+/Pv/6T3EmBodgBIz/Afk68r7EsAkJohMTZfX9iPAACAggQAABQkAEjNhWJj8/WF/QgA0jMkxuTrCvvyNkCGYFgALGMHAAAKEgAAUJAAAICCBAAAFCQAAKAgAQAABQkAAChIAABAQQIAAAoSAABQkF8FzBA++ea3ei8BQvnJv/1r7yUQnB0A0jP84SH/LrhFAJCaH3JwmX8fXCMAAKAgAQAABQkAUnOhE1zm3wfXCADS80MOHvLvglu8DZAh+GEHsIwdAAAoSAAAQEECAAAKEgAAUJAAAICCBAAAFORtgADc9JXv/HT233336uWOK6EVAQDAA0sG/q2PFQQxCQAApmnaNvTnfl4xEIcAAChur8F/7bGEQH8CgCG47znZ9fh11kcO/kuPLQT68S4A0jP8GcHR38c9h/99UdZR0ZPeC3h29+J97zWQl+HPaPbeCYg8cCvuBrx987rbHLYDAFBE5OE/TfHXNxoBAFBAluGaZZ0jEACk1uPCKdjLXt/P2YZqtvVmJQBITwQwAsP/i7KuOxMXAQIMaoQhOvqFgS4CBKCpEYb/NI3zPCISAACDGW1ojvZ8ohAAAFCQAAAYyKhny6M+r54EAMAgRh+Soz+/owkAAChIAAAMoMrZcZXneQQBAAAFCQCA5PY6K/7lD768y+fdyi5AGwIAgIt++YMvhw0BtnnaewHQwiff/FbvJVBMtXtQnCLg6z/8Q+eV0IodANIz/Okhyvfd0dvhUXYEvAywnQAgtSg/hKmp8vdflBBgPQEAwGpCIC8BAMBmQiAfAUBq1S7EIpbe338RXwc/MgQiPv9MBADp9f4hTE2+766zIxCftwEyBD+MISZvH4zLDgAAu7MjEI8AAOAwQiAOAQDA4YRAf64BAOBwrgnoTwAAcBiDPw4BAMDuDP54BAAAuzH44xIAADRn8McnAACSevfqZbhfh3vk4H/36uVhjzUiAQDAZs748xEADKHyfdmZx6+L3ofBn5dfBER6hj9z+D5p6+s//IPhn5wAIDU/1FlixO+Xo18HjzL4vf6/nZcAALgpwtCnLQEAwEUG/7i8BEBqLuxiiVG/X/baDo86/G3/tyEASG/UH+q05fsEvuhJ7wU8u3vxvvcaAEYQ7ZcC7WG0s/+3b153m8N2AACgIAEAMIjRzo7Pjf78jiYAAAYy6pAc9Xn1JAAAoCABADCY0c6WR3s+UQgAgAGNMjRHeR4RCQCAQWUfntnXH50AABhY1iGadd2ZCACAwWUbptnWm5UAACggy1DNss4RCACAIqIP1+jrG43bAQMUchqyke4bYPD3YQcAoKAoQzfKOiqyAwBQVM/dAIO/PwEAUNyRIWDwxyEAAJim6YvDuWUMGPoxCQAAHjgf2kuCwMDPQQAAcJOhPh7vAgCAggQAABQkAACgIAEAAAUJAAAoSAAAQEECAAAKEgAAUJAAAICCBAAAFCQAAKAgAQAABQkAAChIAABAQQIAAAoSAABQkAAAgIIEAAAUJAAAoCABAAAFCQAAKEgAAEBB3QPg7ZvXT3qvAQCO1nv+dQ8AAOB4AgAAChIAAFCQAACAggQAABQUIgB6XwkJAEeKMPdCBAAAcCwBAAAFCQAAKChMAER4PQQA9hZl3oUJAADgOAIAAAoKFQBRtkUAYA+R5lyoAAAAjiEAAKCgcAEQaXsEAFqJNt/CBQAAsL+QARCtkgBgi4hzLWQAAAD7EgAAUFDYAIi4XQIAS0WdZ2EDAADYT+gAiFpNADBH5DkWOgCmKfbBA4BLos+v8AEAALSXIgCiVxQA3JdhbqUIAACgrTQBkKGmACDLvEoTANOU56ACUFOmOZUqAKYp18EFoI5s8yldAAAA26UMgGyVBcDYMs6llAEwTTkPNgDjyTqP0gbANOU96ACMIfMcSh0A05T74AOQV/b5kz4Apin/FwGAXEaYO0MEAACwzDABMEKNARDfKPNmiCdx7tndi/e91wDAWEYZ/CfD7ADcN9oXCYC+RpwrQwbANI35xQLgeKPOk2EDYJrG/aIBcIyR58jQATBNY3/xANjP6PNj6Cd3zsWBANwy+uA/GX4H4L4qX1QA1qk0J0oFwDTV+uICMF+1+VDqyZ7zkgAA1Qb/ScknfU4IANRTdfCflHsJ4DHVvwkAqvFz3w7AA3YDAMZl8P8/B+IKMQCQn6H/OAdlBiEAkI/Bf52Ds5AYAIjL0J/PgdpADAD0Z+iv46A1JAgA9mfgt+EgHkAYACxn0AMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAOP8LJPNTp5VO6kMAAAAASUVORK5CYII=';

// Decode base64 to buffer once at module load
const ICON_BUFFER = Buffer.from(ICON_BASE64, 'base64');

/**
 * Get the app icon as a NativeImage.
 * 
 * On Linux, tries file path first for better X11/Wayland compatibility,
 * then falls back to embedded base64 buffer.
 * 
 * NOTE: On Linux desktop environments (GNOME, KDE, Cinnamon, etc.), the taskbar
 * icon is typically resolved via WM_CLASS matching with a .desktop file, not via
 * the window icon property. This means the icon will only appear properly in the
 * taskbar when the app is installed (via .deb, .AppImage, etc.) and has a 
 * corresponding .desktop file. In dev mode, the taskbar may show a generic icon.
 */
export function getAppIcon(): Electron.NativeImage {
  // Try to load from file path first (better X11 _NET_WM_ICON support)
  const possiblePaths = [
    join(__dirname, '../../build/icon.png'),           // Dev mode
    join(process.resourcesPath || '', 'build/icon.png'), // Production
    join(app.getAppPath(), 'build/icon.png'),          // App path
  ];
  
  for (const iconPath of possiblePaths) {
    if (existsSync(iconPath)) {
      const icon = nativeImage.createFromPath(iconPath);
      if (!icon.isEmpty()) {
        return icon;
      }
    }
  }
  
  // Fall back to embedded base64
  return nativeImage.createFromBuffer(ICON_BUFFER);
}

/**
 * Get the tray icon (resized for system tray, typically 22x22)
 */
export function getTrayIcon(): Electron.NativeImage {
  return getAppIcon().resize({ width: 22, height: 22 });
}
